name: Deploy React App to EC2

on:
  push:
    paths:
      - 'react-app/**'  # 'react-app' 디렉토리에 있는 파일이 변경되면 트리거됩니다.
    branches:
      - master  # master 브랜치에 푸시할 때 워크플로를 실행합니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd react-app && npm install

    - name: Build React app
      run: cd react-app && npm run build

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_KEY }}
        PORT: ${{ secrets.EC2_PORT }}
      run: |
        echo "${KEY}" > key.pem
        chmod 400 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem -r react-app/build/* $USERNAME@$HOST:/var/www/html/
        ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "sudo systemctl restart nginx"
